# Use a base image with your desired OS
FROM ubuntu:latest

# Set environment variables
ENV FLUTTER_HOME=/flutter \
    PATH=$PATH:/flutter/bin

# Install required dependencies
RUN apt-get update && \
    apt-get install -y \
    git \
    curl \
    unzip \
    xz-utils \
    libglu1-mesa && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Flutter
RUN git clone https://github.com/flutter/flutter.git $FLUTTER_HOME

# Add Flutter to the PATH
ENV PATH $PATH:$FLUTTER_HOME/bin/cache/dart-sdk/bin

# Verify Flutter installation and check the version
RUN flutter --version

COPY entrypoint.sh /entrypoint.sh

# Set working directory
# WORKDIR /app

# Command to execute when the container starts
ENTRYPOINT ["/entrypoint.sh"]