FROM node:16.20 AS node_base

RUN echo "NODE Version:" && node --version
RUN echo "NPM Version:" && npm --version

FROM ubuntu:18.04

COPY --from=node_base /usr/local/bin /usr/local/bin

# Prerequisites
#  RUN apt update && apt install -y curl git unzip xz-utils zip libglu1-mesa openjdk-8-jdk wget
RUN apt update && apt install -y curl git unzip xz-utils zip libglu1-mesa openjdk-17-jdk wget

# Set up new user
RUN useradd -ms /bin/bash developer
USER developer
WORKDIR /home/developer
   
# Prepare Android directories and system variables
# RUN mkdir -p Android/sdk
RUN mkdir -p Android/sdk/cmdline-tools/latest
ENV ANDROID_SDK_ROOT /home/developer/Android/sdk
RUN mkdir -p .android && touch .android/repositories.cfg
   
# Set up Android SDK
# ARG SDK_VERSION=sdk-tools-linux-3859397
ARG ANDROID_BUILD_TOOLS_VERSION=33.0.2
ARG ANDROID_SDK_PLATFORM_TOOLS_VERSION=34.0.4
ARG ANDROID_SDK_COMMANDLINE_TOOLS_VERSION=9.0
ARG ANDROID_PLATFORM_VERSION="android-33"

RUN wget -O sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip

# RUN wget -O sdk-tools.zip https://developer.android.com/tools/releases/platform-tools#:~:text=Download%20SDK%20Platform%2DTools%20for%20Linux
RUN unzip sdk-tools.zip && rm sdk-tools.zip
# RUN mv cmdline-tools Android/sdk/cmdline-tools/latest
RUN cp -r ./cmdline-tools/. ./Android/sdk/cmdline-tools/latest
# RUN rm ./cmdline-tools

RUN cd Android/sdk/cmdline-tools/latest/bin && yes | ./sdkmanager --licenses
RUN cd Android/sdk/cmdline-tools/latest/bin && ./sdkmanager "build-tools;29.0.2" "platform-tools" "platforms;android-29" "sources;android-29"
ENV PATH "$PATH:/home/developer/Android/sdk/platform-tools"

# Download Flutter SDK
RUN git clone https://github.com/flutter/flutter.git
ENV PATH "$PATH:/home/developer/flutter/bin"
   
# Run basic check to download Dark SDK
RUN flutter doctor
