name: PR Comment Trigger

on:
  issue_comment:
    types: [created]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check for specific comment
        if: contains(github.event.comment.body, '/e2e')
        run: |
          # Actions to perform when the specific comment is added
          echo "E2E tests triggered"
    
      - name: Check for specific comment
        run: |
          # Actions to perform when the specific comment is added
          echo "Comment received => ${{ github.event.comment.body }}"

    
